version: '3.8'

services:
  db:
    image: mysql:8.0
    restart: always
    env_file:
      - .env.docker
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    env_file:
      - .env.docker
    depends_on:
      - db

volumes:
  db_data:
